using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NII.Database_Classes
{
	class DbContextInitializer : DropCreateDatabaseAlways<NIIDbContext>
	{
		protected override void Seed(NIIDbContext db)
		{
            List<Sample> samples = new List<Sample>()
            {   // http://www.ellatha.com/eve/processed_materiallist.asp?cmd=resetall
                new Sample { Title = "Aqueous Liquids",		     Quantity = "5117 m3",		Description = "The abundance of water on terrestrial planets is often a misconception: What many refer to offhandedly as \"water\" is often an amalgamation of many liquids, microscopic particles, and saturated compounds combined with water and other liquids. Aqueous liquids represent those liquids from which pure water can be separated easily from waste or hazardous particles, but only using the proper equipment" },
                new Sample { Title = "Autotrophs",			     Quantity = "2290 m3",		Description = "At the very bottom of the food chain are autotrophs, those organisms that produce carbohydrates, proteins, and fats for higher life forms to consume. When properly gathered and ordered, they can be plied into industrial fibers, which then go on to contribute to advanced material technologies. " },
                new Sample { Title = "Base Metals",			     Quantity = "314 m3",		Description = "Iron and nickel are two widespread, easily recognized examples of base metals, or those metals that oxidize relatively easily. Their tremendous usefulness in numerous applications ensures that base metals are always in high demand. Thankfully, so is their abundance on most planetary surfaces. " },
                new Sample { Title = "Carbon Compounds",	     Quantity = "418 m3",		Description = "Often referred to as the building blocks of life, carbon compounds form the basis of most organic material; hence, they are ideally suited for use in the early development of advanced, reactive molecules, such as those used in biofuel and supertensile structures. " },
                new Sample { Title = "Complex Organisms",	     Quantity = "912 m3",		Description = "Organic flora and fauna growing on worlds across the cluster technically qualify as “alien life,” though none of it has registered as sentient. However, their usefulness as comestibles or building materials in other areas of industry is invaluable. " },
                new Sample { Title = "Felsic Magma",		     Quantity = "537 m3",		Description = "The churning core of lava planets is rife with felsic magma, or silicate material that is infused with lighter elements, from which basic silicon and other atomic matter may be extracted. Silicon is abundant on many terrestrial planets, but the fastest and easiest way to obtain it, given advances in planetary mining processes, is from felsic magma. " },
                new Sample { Title = "Heavy Metals",		     Quantity = "3780 m3",		Description = "In small quantities, heavy metals are vital to life, providing essential minerals for biological processes. In bulk, they are commonly found in most construction materials, forming the most basic components of computer electronics and reinforced structures. " },
                new Sample { Title = "Ionic Solutions",		     Quantity = "818 m3",		Description = "An electrolyte found in a raw, natural form is called an ionic solution, especially in terms of planetary astronomy. Only after a lengthy process of extraction and refining can the resulting fluid go on to be used for medical, industrial, or nutritive applications." },
                new Sample { Title = "Micro Organisms",		     Quantity = "827 m3",		Description = "Any life form too small to be detected by the unaided human eye qualifies as a microorganism, yet as a whole, this classification of biology covers an enormous and diverse spectrum. From parasites and viruses to fungi and insects, the study or industrial application of these creatures is just as broad." },
                new Sample { Title = "Noble Gas",			     Quantity = "1730 m3",		Description = "This colorless, odorless, and usually nonflammable substance is one of seven known monoatomic gases, or those that do not easily combine with other atoms. They are thus well suited for a variety of manufacturing implementations. " },
                new Sample { Title = "Noble Metals",		     Quantity = "1500 m3",		Description = "Highly resistant to corrosion and oxidation, noble metals are somewhat rarer than base metals, yet they are just as sought after for their different electrical, material, and chemical attributes. When painstakingly refined and purified, some noble metal ores can produce \"precious metals\"." },
                new Sample { Title = "Non-CS Crystals",		     Quantity = "620 m3",		Description = "The orderly, compact nature of crystals makes them well suited for a staggering array of manufacturing processes, in which they are just as often the product of the factory as they are incorporated into many of the tools and machinery used therein." },
                new Sample { Title = "Planktic Colonies",	     Quantity = "718 m3",		Description = "Harvested in mass quantities, planktic colonies are used for much more than just a bulk food source that flourishes in water-rich environments. Their cumulative biomass has advanced properties that contribute to some of the most advanced material and medical sciences in New Eden. " },
                new Sample { Title = "Reactive Gas",		     Quantity = "6200 m3",		Description = "Consisting of any number of volatile atomic structures, reactive gases are the most useful when applied to the fields of explosives, molecular restructuring, and electrical conduction. Great care must be taken when storing or transporting any sizeable quantity." },
                new Sample { Title = "Suspended Plasma",	     Quantity = "7400 m3",		Description = "When found in harvestable quantities beyond the unapproachable heat of an active star, plasma is said to be in a “suspended” state. Specialized electronic equipment is used to attract the ionized particles into collection tubes, after which it can be stored, transported, or applied to a variety of technologies." },
                new Sample { Title = "Bacteria",			     Quantity = "990 m3",		Description = "The term “bacteria” covers a wide, diverse family of unicellular microorganisms, from those found in almost every climate in New Eden to those that thrive in the bodies of other living beings. Though some bacteria are known to convey diseases, others are more helpful than harmful to humans. " },
                new Sample { Title = "Biofuels",			     Quantity = "1243 m3",		Description = " The most widely used, renewable solid fuel in the cluster, biofuel production is present in some fashion on almost every inhabited world. A steady fuel source can be maintained in a planetary economy by converting living material directly into energy instead of relying on fossil fuels. " },
                new Sample { Title = "Biomass",				     Quantity = "4000 m3",		Description = "A catch-all term for composite material obtained from living things, biomass has several unique properties that make it ideal for various industrial, commercial, and personal uses. Its most important attribute is that it retains many of its nutrients even after being harvested, transported, and processed. " },
                new Sample { Title = "Chiral Structures",	     Quantity = "6000 m3",		Description = "A chiral structure is a crystal that is unsymmetrical, which makes it volatile in some situations but ideal for conductivity, especially in micro-circuitry. Using semi-rare chiral structures in electronics has allowed for an unprecedented advancement in the field of miniaturization. " },
                new Sample { Title = "Electrolytes",		     Quantity = "5432 m3",		Description = "This conductive liquid is able to carry an electrical current due to its unique ionic properties, making it ideal for use as a reactive coolant, a high-energy fuel, or a transference medium for power plants. " },
                new Sample { Title = "Industrial Fibers",        Quantity = "4700 m3",		Description = "The main difference between fibers used in industry and those created for civilian use is the trade-off of comfort for tensile strength and durability. This allows industrial fibers to be used in more severe environments, from electronic component shielding on hostile worlds to solar sails in the frigid void of space. " },
                new Sample { Title = "Oxidizing Compound",	     Quantity = "5800 m3",		Description = "Converting various matter from its basic state to an oxidized form requires an oxidizing compound, the most effective of which is a powerful agent made from pressurized reactive gas. Special containers are required to keep the compound from causing significant damage to common metals and organic life. " },
                new Sample { Title = "Oxygen",				     Quantity = "8100 m3",		Description = "Oxygen is a commodity in constant demand. While most stations have their own supply units, smaller depots and space crafts rely on imports. " },
                new Sample { Title = "Plasmoids",			     Quantity = "3399 m3",		Description = "In the early days of humanity’s return to space flight, scientists Planto and Ginch co-discovered a self-sustaining natural structure made entirely from plasma suspended in a planetary magnetic field. Since then, the term has been applied to any such construct, whether occurring under normal conditions or produced artificially using electrical currents. " },
                new Sample { Title = "Precious Metals",		     Quantity = "4566 m3",		Description = "A cousin of noble metals, precious metals are named as such because of how infrequently they appear on terrestrial worlds, where they were first encountered. It wasn’t until centuries later that their unique chemical properties were discovered and industrial relevance exploited. " },
                new Sample { Title = "Proteins",			     Quantity = "1833 m3",		Description = "One of the most basic components of biological life, proteins form the core DNA structure and are involved in almost every process that sustains a living being. Harvested at the microscopic level, proteins can be put to use in everything from medical genetics to nanite technology. " },
                new Sample { Title = "Reactive Metals",		     Quantity = "1079 m3",		Description = "Very dense metals are often called reactive metals, as their ability to conduct electrical currents and absorb heat is unparalleled. Rarely found in a natural solid state, they are instead usually assembled on an atomic level from particulate matter found in other forms. " },
                new Sample { Title = "Silicon",				     Quantity = "999 m3",		Description = "As one of the most common elements in the universe, it’s no surprise that silicon has found its way into almost every aspect of manufacturing, resulting in a steady price and perpetual mining operations on most solid planets. " },
                new Sample { Title = "Toxic Metals",		     Quantity = "500 m3",		Description = "Derived from heavy metals, toxic metals are those that have no biological function and are in fact poisonous to most living creatures. " },
                new Sample { Title = "Water",				     Quantity = "10000 m3",	    Description = "Water is one of the basic conditional elements of human survival. Most worlds have this compound in relative short supply and hence must rely on starship freight. " },
                new Sample { Title = "Silicate Glass",		     Quantity = "988 m3",		Description = "Silicate glass is a common construction material, in constant demand throughout New Eden, whether in planetary structures or reinforced for use in space vessels. " },
                new Sample { Title = "Rocket Fuel",			     Quantity = "20000 m3",	    Description = "The properties of this carefully refined liquid make it ideal for controlled combustion whether in or outside of atmospheric environments; its severe volatility requires special containers to resist most forms of impact, high temperatures, and electrical activity during storage and transportation. " },
                new Sample { Title = "Polytextiles",		     Quantity = "1811 m3",		Description = "Composite materials, both synthetic and natural, are used in the creation of polytextiles, durable fabrics that see widespread use in the clothing industry, solar sail manufacture, and even classic art. " },
                new Sample { Title = "Polyaramids",			     Quantity = "912 m3",		Description = "Polyaramid textiles are produced when industrial fibers are harvested from autotrophic life forms and subjected to intense pressure using reactive gas pistons. Able to absorb a startling amount of kinetic energy, sheets of this miraculous material can be form-fitted to just about any structure, protecting it from anything but weapons-grade impact forces." },
                new Sample { Title = "Oxides",				     Quantity = "1000 m3",		Description = "Technically, any chemical compound that contains at least one oxygen atom is an oxide, though some are far more valuable than others. Once broken down and separated from waste material, many oxides can be applied to various industrial processes." },
                new Sample { Title = "Microfiber Shielding",     Quantity = "555 m3",		Description = "Using advanced residual substrate isolation technology, silicon weave is threaded through layers of tough organic fibers. The resulting microfiber shielding is incredibly resilient and retains the microscopic profile required to shield miniaturized electronics. " },
                new Sample { Title = "Fertilizer",			     Quantity = "50000 m3",	    Description = "Fertilizer is particularly valued on agricultural worlds, where there is constant supply for all commodities that boost export value. " },
                new Sample { Title = "Enriched Uranium",	     Quantity = "200 m3",		Description = "Enriched Uranium is used in many kinds of manufacturing and as a fuel, making it a steady trade commodity. Enriched Uranium is generally manufactured by combining standard semiconductor PVD methods with ionic separation by means of mass spectrometry. " },
                new Sample { Title = "Supertensile Plastics",    Quantity = "1713 m3",		Description = "“Hyperoxidation” was the term given to the process of rapidly fossilizing the carbon structures, readily available in the form of biomass, which forms the basic framework of supertensile plastics. The only amorphous solid known to retain the resilience of other such materials while also adopting conductive properties, supertensile plastic is highly sought after for a wide range of industrial applications." },
                new Sample { Title = "Synthetic Oil",		     Quantity = "642 m3",		Description = "Since original oil can be harvested only from a world with a long biological history, synthetic oil has become frequently produced in laboratories all over known space. " },
                new Sample { Title = "Test Cultures",		     Quantity = "5010 m3",		Description = "When bacteria are allowed to thrive in a water-based environment, they undergo generational transformations that can be monitored and documented, providing research data invaluable to numerous scientific fields. " },
                new Sample { Title = "Synthetic Synapses",       Quantity = "3 m3",		    Description = "The wide range of uses for synthetic synapses is largely due to the fact that they are able to serve double duty as electrical conduit and as replacements or additions to biological nervous systems. This allows them to be used in computers, cybernetics, and artificial intelligence equipment. " },
                new Sample { Title = "Vaccines",			     Quantity = "3230 m3",		Description = "Living creatures can be trained to defend themselves from harmful diseases by introducing a minute sample of pathological strains, tremendously improving their immune systems and allowing them to endure prolonged exposure to harmful contagions. " },
				new Sample { Title = "Condensates",			     Quantity = "1112 m3",		Description = "Oxidized coolant is required to produce the temperatures needed to force rare particles to condense out of ordinary matter, which is the most economic way to produce valuable base elements in bulk." },
				new Sample { Title = "Gel-Matrix Biopaste",      Quantity = "1643 m3",      Description = "Gel-matrix biopaste is a highly unstable substance that must be formed from elements that don't combine under normal circumstances. Forcing them to do so requires enormous amounts of energy, but the end product is invaluable to high-end electronics and cybernetic medicine." },
				new Sample { Title = "Cryoprotectant Solution",  Quantity = "4500 m3",		Description = "The base elements present in certain synthetic oils can, at extreme temperatures, produce habitable environments for genetically engineered extremophile. The byproduct of their rapid life-death cycle is a highly thermal resistant solution ideal for hybrid electronics." },
				new Sample { Title = "Biotech Research Reports", Quantity = "5400 m3",		Description = "As the core fundamentals of organic life constantly evolve and develop on micro and macro levels, the constant production and distribution of biotech research is a mandatory part of ongoing advances in countless scientific disciplines." }
			};
			samples.ForEach(smp => db.Samples.Add(smp));
            //db.Samples.AddRange(samples);
			db.SaveChanges();

			List<Equipment> equipments = new List<Equipment>
            {
                new Equipment { Title = "Transmitter",				Quantity = 500,		Description = "This electronic device generates and amplifies a carrier wave, modulates it with a meaningful signal derived from speech or other sources, and radiates the resulting signal from an antenna or some other form of transducer. "},
                new Equipment { Title = "Water-Cooled CPU",			Quantity = 250,		Description = "Despite how ancient the technology is, there is still no method more cost-effective for cooling computer processing units than ordinary water, which can be heated and cooled rapidly via any number of proven methods. Most often, thermally conductive tubing makes its way through all of the vital components and over heat sinks, helping to regulate operating temperatures. "},
                new Equipment { Title = "Superconductors",			Quantity = 100,		Description = "Required for highly advanced technologies too numerous to mention to function properly, these conduits are made from super-cooled materials that function as perfect conductors, having an effective electrical resistance of zero."},
                new Equipment { Title = "Nanites",					Quantity = 1000,	Description = "Though they are only simple machines and very small, nanites can be used to achieve miraculous medical results in small amounts or astounding feats of engineering in mass quantities."},
                new Equipment { Title = "Miniature Electronics",	Quantity = 2500,	Description = "Advances in molecular chemistry and nanite-reduced computer chips have made almost every form of miniature electronics possible, from the simple holovid viewer and missile tracking systems to wetware cybernetics and quantum entanglement communications. "},
                new Equipment { Title = "Mechanical Parts",			Quantity = 10000,	Description = "These basic elements of all mechanical hardware can come in virtually any shape and size, although composite or modular functionality is highly advantageous in today's competitive market. Factories and manufacturers take these parts and assemble them into finished products, which are then sold on the market. "},
                new Equipment { Title = "Construction Blocks",		Quantity = 700,		Description = "Metal girders, plasteel concrete, and fiber blocks are all common construction materials used in almost every large-scale building or manufacturing project throughout New Eden."},
                new Equipment { Title = "Biocells",					Quantity = 7000,	Description = "Similar to an ancient battery, a biocell instead uses biofuels distilled from organic material and precious metals to produce an electrical current in a self-contained, modular unit. However, modern biocells dwarf the capabilities of ancient batteries by several orders of magnitude. "},
                new Equipment { Title = "Supercomputers",			Quantity = 15,		Description = "When an individual computer system incorporates a wide range of networked utilities, layered processors, and redundant memory cores, it is said to have evolved into a supercomputer. Such systems can be put to use managing spaceships, starbases, or even entire planetary administrations. "},
                new Equipment { Title = "Smartfab Units",			Quantity = 1200,	Description = "These tiny cubes form the building blocks of many simple structures, from basic walls and doors to entire homes and even industrial office spaces. Whenever a sufficient number of smartfab units are placed together and have been programmed with the same instructions, they will automatically combine to form some portion of that object and then become inert in their new form. With adequately detailed blueprints, there is theoretically no limit to the complexity of object or structure these clever devices can create. "},
                new Equipment { Title = "Robotics",					Quantity = 4400,	Description = "These pre-programmed or remote control mechanical tools are commonly used in mass production facilities, hazardous material handling, or dangerous front line military duties such as bomb disarming and disposal."},
                new Equipment { Title = "Planetary Vehicles",		Quantity = 2200,	Description = "Tracked, wheeled and hover vehicles used within planetary atmosphere for personal and business use. "},
                new Equipment { Title = "Nuclear Reactors",			Quantity = 10,		Description = "This power core is able to convert heavy elements into electricity by way of nuclear fission, splitting atoms to produce thermal energy on a massive scale. If they are properly shielded and cooled, there are few safer, cleaner ways to power buildings or large vehicles. "},
                new Equipment { Title = "Hazmat Detection Systems", Quantity = 55,		Description = "A critical component of space stations, starships, or any other isolated environment, these tiny devices are set to trigger alarms when the genetically engineered viruses inside mutate — which means that they’ve encountered a significant dose of radiation, natural contaminant, or airborne pathogen, signifying that the surrounding crew is in danger. "},
                new Equipment { Title = "Guidance Systems",			Quantity = 12000,	Description = "An electrical device used in targeting systems and tracking computers. "},
                new Equipment { Title = "Data Chips",				Quantity = 15000,	Description = "A small wafer of semiconductor material that forms the base for an integrated circuit. "},
                new Equipment { Title = "Camera Drones",			Quantity = 1500,	Description = "Most visibly used in starship development, especially on capsuleer craft, other types of camera drones are also employed in the fields of nano-medicine, surveillance, and entertainment."},
                new Equipment { Title = "Biotech Research Reports", Quantity = 8000,	Description = "As the core fundamentals of organic life constantly evolve and develop on micro and macro levels, the constant production and distribution of biotech research is a mandatory part of ongoing advances in countless scientific disciplines. "},
            };
			equipments.ForEach(eq => db.Equipment.Add(eq));
            //db.Equipment.AddRange(equipments);
			db.SaveChanges();
						
			List<Technician> technicians = new List<Technician>
			{	// https://www.randomcodegenerator.com/en/generate-codes
                new Technician { Name = "Coco Garza",        Age = 33, Position = "Analytical Lab Technician",         Personal_Identification_Number = "THN0001", Qualification = "Engineering analysis",     EducationalBackground = "Massachusetts Institute of Technology (MIT), 77 Massachusetts Avenue Cambridge, MA 02139 United States",		DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Juniper Parks",     Age = 34, Position = "Chemical Technician",               Personal_Identification_Number = "THN0002", Qualification = "Chemistry",                EducationalBackground = "Stanford University, 450 Serra Mall Stanford, CA 94305 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Anique Tucker",     Age = 35, Position = "Computer Programmer",               Personal_Identification_Number = "THN0003", Qualification = "Linear networks",          EducationalBackground = "Harvard University, Cambridge, MA 02138 United States",															DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Fern Macias",       Age = 36, Position = "Development Technologist",          Personal_Identification_Number = "THN0004", Qualification = "Manufacturing Skills",     EducationalBackground = "California Institute of Technology (Caltech), 1200 East California Boulevard Pasadena, CA 91125 United States", DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Taylor Nava",       Age = 37, Position = "Environmental Research Assistant",  Personal_Identification_Number = "THN0005", Qualification = "Fluid mechanics",          EducationalBackground = "University of Chicago, 5801 South Ellis Avenue Chicago, IL 60637 United States",								DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Finley Sierra",     Age = 38, Position = "Genetic Counselor",                 Personal_Identification_Number = "THN0006", Qualification = "Fluid mechanics",          EducationalBackground = "Princeton University, Princeton, NJ 08544 United States",														DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Olive Haworth",     Age = 39, Position = "Hardware Designer",                 Personal_Identification_Number = "THN0007", Qualification = "Fluid mechanics",          EducationalBackground = "Cornell University, Day Hall Lobby Ithaca, NY 14853 United States",												DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Deryn Murphy",      Age = 30, Position = "Laboratory Assistant",              Personal_Identification_Number = "THN0008", Qualification = "Chemistry",                EducationalBackground = "Yale University, P.O. Box 208236 New Haven, CT 06520 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Serene Barnett",    Age = 22, Position = "Laboratory Manager",                Personal_Identification_Number = "THN0009", Qualification = "Manufacturing Skills",     EducationalBackground = "Johns Hopkins University, Baltimore, MD 21218 United States",													DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Deanna Hopkins",    Age = 23, Position = "Laboratory Technician",             Personal_Identification_Number = "THN0010", Qualification = "Manufacturing Skills",     EducationalBackground = "Columbia University, 2960 Broadway New York, NY 10027 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Carson Felix",      Age = 24, Position = "Medical Research Assistant",        Personal_Identification_Number = "THN0011", Qualification = "Fluid mechanics",          EducationalBackground = "University of Pennsylvania, 3451 Walnut Street Philadelphia, PA 19104 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Birdie Pruitt",     Age = 25, Position = "Medical Research Technician",       Personal_Identification_Number = "THN0012", Qualification = "Machine design",           EducationalBackground = "Duke University, 2138 Campus DriveBox 90586 Durham, NC 27708 United States",									DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Kimberly Shepherd", Age = 26, Position = "Organic Lab Research Assistant",    Personal_Identification_Number = "THN0013", Qualification = "Machine design",           EducationalBackground = "University of Michigan, Ann Arbor, MI 48109 United States",														DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Eartha Vickers",    Age = 27, Position = "Pharmaceutical Research Technician", Personal_Identification_Number = "THN0014", Qualification = "Welding",                  EducationalBackground = "University of California, Berkeley (UCB), 110 Sproul Hall Berkeley, CA 94720 United States",					DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Shannon Mccarthy",  Age = 28, Position = "Power Regulator",                   Personal_Identification_Number = "THN0015", Qualification = "Welding",                  EducationalBackground = "Northwestern University, 633 Clark Street Evanston, IL 60208 United States",									DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Summer Ramirez",    Age = 29, Position = "Process Engineer",                  Personal_Identification_Number = "THN0016", Qualification = "Electronic Engineering",   EducationalBackground = "Northwestern University, 375 E. Chicago Avenue Chicago, IL 60611 United States",								DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Mala Kelly",        Age = 50, Position = "Product Engineer",                  Personal_Identification_Number = "THN0017", Qualification = "Astronautic Engineering",  EducationalBackground = "University of California, Los Angeles (UCLA), 405 Hilgard Avenue Los Angeles, CA 90095 United States",			DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Emma Bowers",       Age = 21, Position = "Product Test Specialist",           Personal_Identification_Number = "THN0018", Qualification = "Astronautic Engineering",  EducationalBackground = "University of California, San Diego (UCSD), 92093 La Jolla, CA 92093 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Bela Bowman",       Age = 22, Position = "Quality Assurance Technologist",    Personal_Identification_Number = "THN0019", Qualification = "Astronautic Engineering",  EducationalBackground = "Carnegie Mellon University, 5000 Forbes Avenue Pittsburgh, PA 15213 United States",								DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Sasha Terrell",     Age = 23, Position = "Research Assistant",                Personal_Identification_Number = "THN0020", Qualification = "Electronic Engineering",   EducationalBackground = "New York University (NYU), 10012 70 Washington Square South, 12S New York NY 10012, United States",				DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Eshe Lynn",         Age = 24, Position = "Research Technician",               Personal_Identification_Number = "THN0021", Qualification = "Molecular Engineering",    EducationalBackground = "Brown University, 02912 Providence, RI 02912 United States",													DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Terra Parkinson",   Age = 25, Position = "Research and Development Tester",   Personal_Identification_Number = "THN0022", Qualification = "Molecular Engineering",    EducationalBackground = "University of Wisconsin-Madison, 53706 500 Lincoln Drive Madison, WI 53706 United States",						DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Snow Prentice",     Age = 26, Position = "Research and Development Tester",   Personal_Identification_Number = "THN0023", Qualification = "Robotics",                 EducationalBackground = "University of Washington, 98005 12280 District Way NE Bellevue, WA 98005 United States",						DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "May Lennon",        Age = 29, Position = "Science Technician",                Personal_Identification_Number = "THN0024", Qualification = "Electronic Engineering",   EducationalBackground = "University of Texas at Austin, 78712 1 University Station Austin, TX 78712 United States",						DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Morena Malone",     Age = 27, Position = "Software Developer",                Personal_Identification_Number = "THN0025", Qualification = "Linear networks",          EducationalBackground = "University of Illinois at Urbana-Champaign, 61801 901 West Illinois Street Urbana, IL 61801 United States",		DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Malea Hayes",       Age = 39, Position = "Software Engineering Assistant",    Personal_Identification_Number = "THN0026", Qualification = "Linear networks",          EducationalBackground = "Georgia Institute of Technology, 30332 Atlanta, GA 30332 United States",										DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Sienna Frazier",    Age = 28, Position = "Structural Engineer",               Personal_Identification_Number = "THN0027", Qualification = "Robotics",                 EducationalBackground = "University of North Carolina, Chapel Hill, 27599 CB #2200, Jackson Hall Chapel Hill, NC 27599 United States",	DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Bianca Hutchinson", Age = 23, Position = "Technical Support Technician",      Personal_Identification_Number = "THN0028", Qualification = "Robotics",                 EducationalBackground = "Boston University, 02215 One Silber Way Boston, MA 02215 United States",										DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Skye Greene",       Age = 21, Position = "Laboratory Assistant",              Personal_Identification_Number = "THN0029", Qualification = "Machine design",           EducationalBackground = "The Ohio State University, 43210 Enarson Hall 154 W 12th Avenue Columbus, OH 43210 United States",				DateOfEmployment = new DateTime(2016,6,28) },
                new Technician { Name = "Abbie Lambert",     Age = 29, Position = "Laboratory Assistant",              Personal_Identification_Number = "THN0030", Qualification = "Machine design",           EducationalBackground = "Rice University, 77005 6100 MainHouston, TX 77005 United States",												DateOfEmployment = new DateTime(2016,6,28) }
            };
			technicians.ForEach(t => db.Technicians.Add(t));
			//db.Technicians.AddRange(technicians);
			db.SaveChanges();
						
			List<Scientist> scientists = new List<Scientist>
			{	// Universities https://www.topuniversities.com/university-rankings-articles/world-university-rankings/top-universities-us-2018
                new Scientist { Name = "Agalle Vacoloure",   Age = 43, Position = "Analytical Services Chemist",       Personal_Identification_Number = "SCS0001", Qualification = "Advanced Laboratory Operation", EducationalBackground = "Pennsylvania State University, 16802 201 Old Main University Park, PA 16802 United States",						DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Olarie Lacenten",	 Age = 44, Position = "Bioanalytical Scientist",           Personal_Identification_Number = "SCS0002", Qualification = "Advanced Laboratory Operation", EducationalBackground = "Washington University in St. Louis, 63130 One Brookings Drive St Louis, MO 63130 United States",					DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Abenar Zindob",		 Age = 45, Position = "Biochemist",                        Personal_Identification_Number = "SCS0003", Qualification = "Advanced Laboratory Operation", EducationalBackground = "Krannert School of Management, 47907-2076 Rawls Hall, Suite 2021 West Lafayette, IN 47907-2076 United States",		DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Avery Perry",		 Age = 46, Position = "Bioinformatics Research Scientist", Personal_Identification_Number = "SCS0004", Qualification = "Plasma Physics",                EducationalBackground = "University of California, Davis, 95616 One Shields Avenue Davis, CA 95616 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Fern Davidson",		 Age = 33, Position = "Cell Biology Scientist",            Personal_Identification_Number = "SCS0005", Qualification = "Plasma Physics",                EducationalBackground = "University of Maryland, College Park, 20742 College Park, MD 20742 United States",									DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Arcadia Mcguire",	 Age = 34, Position = "Chemical Engineer",                 Personal_Identification_Number = "SCS0006", Qualification = "Plasma Physics",                EducationalBackground = "University of Southern California, 90089 University Park Campus Los Angeles, CA 90089 United States",				DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Blossom Guerra",	 Age = 35, Position = "Environmental Data Analyst",        Personal_Identification_Number = "SCS0007", Qualification = "Scientific Networking",         EducationalBackground = "University of California, Santa Barbara (UCSB), 93106 3117 Cheadle Hall Santa Barbara, CA 93106 United States",	DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Ruby Hubbard",		 Age = 42, Position = "Environmental Health Scientist",    Personal_Identification_Number = "SCS0008", Qualification = "Plasma Physics",                EducationalBackground = "Katz Graduate School of Business, 18600 Rohanske nabrezi 671/15A Prague 8, 18600 United States",					DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Vienna Jacobs",		 Age = 36, Position = "Environmental Scientist",           Personal_Identification_Number = "SCS0009", Qualification = "Talocan Technology",            EducationalBackground = "Emory University, 30322 201 Dowman Drive Atlanta, GA 30322 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Ireland Mcgrath",	 Age = 37, Position = "Gene Editing Manager",              Personal_Identification_Number = "SCS0010", Qualification = "Scientific Networking",         EducationalBackground = "Michigan State University, 48824 East Lansing, MI 48824 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Malea Lawrence",	 Age = 39, Position = "Health Research Assistant",         Personal_Identification_Number = "SCS0011", Qualification = "Sleeper Encryption Methods",    EducationalBackground = "University of Minnesota, 55455 240 Williamson Hall, 231 Pillsbury Drive S.E. Minneapolis, MN 55455 United States", DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Carys Foster",		 Age = 33, Position = "Immunology Scientist",              Personal_Identification_Number = "SCS0012", Qualification = "Sleeper Encryption Methods",    EducationalBackground = "University of California, Irvine, 92616 P.O. Box 6050 Irvine, CA 92616 United States",								DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "America Horton",	 Age = 41, Position = "Medical Physics Researcher",        Personal_Identification_Number = "SCS0013", Qualification = "Sleeper Encryption Methods",    EducationalBackground = "Dartmouth College, 03755 Hanover, NH 03755 United States",															DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Brooke Sheridan",	 Age = 30, Position = "Molecular Biologist",               Personal_Identification_Number = "SCS0014", Qualification = "Talocan Technology",            EducationalBackground = "University of Virginia, 22904 P.O. Box 400132 Charlottesville, VA 22904 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Sorrell Russell",	 Age = 35, Position = "Oncology Researcher",               Personal_Identification_Number = "SCS0015", Qualification = "Talocan Technology",            EducationalBackground = "University of Florida, 32611 Gainesville, FL 32611 United States",													DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Gemma Ross",		 Age = 33, Position = "Research Chemist",                  Personal_Identification_Number = "SCS0016", Qualification = "Scientific Networking",         EducationalBackground = "University of Colorado Boulder, Regent Administrative Center 125 552 UCB Boulder, CO 80309 United States",			DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Soleil Wilkinson",	 Age = 31, Position = "Research and Development Chemist",  Personal_Identification_Number = "SCS0017", Qualification = "Sleeper Technology",            EducationalBackground = "University of Rochester, 14627 Rochester, NY 14627 United States",													DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Delta Downs",		 Age = 29, Position = "Safety Data Specialist",            Personal_Identification_Number = "SCS0018", Qualification = "Sleeper Technology",            EducationalBackground = "Mays Business School, 77843-4117 390 Wehner Building College Station, TX 77843-4117 United States",				DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Capri Broughton",	 Age = 43, Position = "Satellite Data Analyst",            Personal_Identification_Number = "SCS0019", Qualification = "Scientific Networking",         EducationalBackground = "University of Illinois, Chicago (UIC), 60680 Box 5220 Chicago, IL 60680 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Bela Doherty",		 Age = 47, Position = "Satellite Data Analyst",            Personal_Identification_Number = "SCS0020", Qualification = "Scientific Networking",         EducationalBackground = "Arizona State University, 85287 University Drive and Mill Avenue Tempe, AZ 85287 United States",					DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Summer Good",		 Age = 41, Position = "Scientific Programmer",             Personal_Identification_Number = "SCS0021", Qualification = "Electromagnetic Physics",       EducationalBackground = "Owen Graduate School of Management, 37203 Management Hall Nashville, 37203 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Carson Kumar",		 Age = 37, Position = "Scientific Programmer",             Personal_Identification_Number = "SCS0022", Qualification = "Electromagnetic Physics",       EducationalBackground = "Case Western Reserve University, 44106 Cleveland, OH 44106 United States",											DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Olive Macdonald",	 Age = 28, Position = "Stem Cell Researcher",              Personal_Identification_Number = "SCS0023", Qualification = "Plasma Physics",                EducationalBackground = "University of Notre Dame, 46556 Notre Dame, IN 46556 United States",												DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Robin Dodd",		 Age = 38, Position = "Structural Biologist",              Personal_Identification_Number = "SCS0024", Qualification = "Quantum Physics",               EducationalBackground = "Georgetown University, 20057 37th and O Streets, NW, Washington, DC 20057 United States",							DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Lake Elliott",		 Age = 39, Position = "Structural Biologist",              Personal_Identification_Number = "SCS0025", Qualification = "Quantum Physics",               EducationalBackground = "The University of Arizona, 1117 E Lowell Tucson, Arizona 85721 United States",										DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Rue Rhodes",		 Age = 49, Position = "Toxicologist",                      Personal_Identification_Number = "SCS0026", Qualification = "Quantum Physics",               EducationalBackground = "Tufts University, 02155 Medford, MA 02155 United States",															DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Brooklyn Wynn",		 Age = 51, Position = "Toxicologist",                      Personal_Identification_Number = "SCS0027", Qualification = "Sleeper Technology",            EducationalBackground = "University of Massachusetts Amherst, MA 01003 Amherst, MA MA 01003 United States",									DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Auburn Buckner",	 Age = 55, Position = "Biochemist",                        Personal_Identification_Number = "SCS0028", Qualification = "Sleeper Technology",            EducationalBackground = "University of Miami, 33124 Coral Gables,Miami, Florida 33124 United States",										DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Dale Tyler",		 Age = 58, Position = "Scientific Programmer",             Personal_Identification_Number = "SCS0029", Qualification = "Electromagnetic Physics",       EducationalBackground = "North Carolina State University, 2801 Founders Drive, 2300 Nelson HallRaleigh, North Carolina 27695 United States", DateOfEmployment = new DateTime(2016,6,28) },
                new Scientist { Name = "Scout Vikander",	 Age = 47, Position = "Scientific Programmer",             Personal_Identification_Number = "SCS0030", Qualification = "Electromagnetic Physics",       EducationalBackground = "University of California, Santa Cruz, 95064 1156 High Street Santa Cruz, CA 95064 United States",					DateOfEmployment = new DateTime(2016,6,28) }
            };
			scientists.ForEach(s => db.Scientists.Add(s));
			//db.Scientists.AddRange(scientists);
			db.SaveChanges();
			
			List<Project> projects = new List<Project>
            {
                new Project { Name = "Organic Mortar Applicators", Term = 65, Location = "Alaska", DateOfBeginning = new DateTime(2017,1,21), Cost = 10000, CodeName = "OMA-17", Description = "While nanites are ideal for many forms of construction, sealing joints between large structural bulkheads is a job best left to organic mortar, a thick gel that actively permeates every microscopic gap between two parts. Due to the aggressive nature of the genetically engineered bacteria that intelligently guides into place the hardening condensate material, this paste is extremely hazardous to humans and must be applied by robots.",
                    Scientists = new List<Scientist> { scientists[0], scientists[5], scientists[8], scientists[15], scientists[20]},
                    Technicians = new List<Technician> { technicians[0], technicians[1], technicians[2], technicians[3], technicians[15], technicians[24]},
                    Samples = new List<Sample> { samples[15], samples[43]},
                    Equipments = new List<Equipment> { equipments[10] } },

                new Project { Name = "Integrity Response Drones", Term = 80, Location = "New Zeland", DateOfBeginning = new DateTime(2018,3,27), Cost = 23000, CodeName = "IRD-24", Description = "Hull breaches are a constant, serious threat during space travel, as well as a dangerous reality to orbital stations, which are too massive to avoid incoming objects. Integrity response drones help mitigate that threat by providing the automated, immediate application of sealants to any detected impact or pressure fracture in the structure they patrol.",
                    Scientists = new List<Scientist> { scientists[2], scientists[14], scientists[19], scientists[20], scientists[29] },
                    Technicians = new List<Technician> { technicians[2], technicians[3], technicians[12], technicians[14], technicians[21] },
                    Samples = new List<Sample> { samples[44] },
                    Equipments = new List<Equipment> { equipments[11], equipments[13] } },

                new Project { Name = "Wetware Mainframe", Term = 165, Location = "USA", DateOfBeginning = new DateTime(2012,8,13), Cost = 500000, CodeName = "WMF-00-19", Description = "So advanced and energy-demanding are wetware mainframes that they require vehicle-scale power cores and the constant attention of maintenance personnel. When operating at peak performance levels, nothing in New Eden can match the raw computing power of these machines, from calculating warp coordinates to administrating the core functions of an entire space station.",
                    Scientists = new List<Scientist> { scientists[17], scientists[19], scientists[21], scientists[28] },
                    Technicians = new List<Technician> { technicians[2], technicians[3], technicians[6], technicians[14], technicians[22], technicians[24], technicians[26] },
                    Samples = new List<Sample> { samples[45], samples[46] },
                    Equipments = new List<Equipment> { equipments[8] } }
            };
			projects.ForEach(p => db.Projects.Add(p));
            //db.Projects.AddRange(projects);            
            db.SaveChanges();
            base.Seed(db);

            //new Equipment { Title = "Wetware Mainframe",		Quantity = 5,		Description = "So advanced and energy-demanding are wetware mainframes that they require vehicle-scale power cores and the constant attention of maintenance personnel. When operating at peak performance levels, nothing in New Eden can match the raw computing power of these machines, from calculating warp coordinates to administrating the core functions of an entire space station. "},
            //new Equipment { Title = "Sterile Conduits",		Quantity = 11,		Description = "Sustaining diverse populations of station inhabitants – many of whom come from different worlds with different ecologies – was a medical nightmare until the development of sterile conduits. Each length of flexible, self-repairing tube is powered by breaking down the chemical energy in the water they convey, which itself is laced with smart vaccines able to identify and destroy almost any known antigen. "},
            //new Equipment { Title = "Self-Harmonizing Power Core", Quantity = 33, Description = "With camera drones diligently monitoring the temperature, radioactivity, and electrical output of these advanced nuclear reactors, instant adjustments can be made to a dynamic, adaptive layer of hermetic membranes, which keeps the power core functioning safely at maximum capacity, with no human attention required whatsoever. "},
            //new Equipment { Title = "Recursive Computing Module", Quantity = 50,	Description = "Not all automated functions are delicate or complicated enough to warrant advanced computer hardware; relatively mundane tasks are best when assigned to an RCM bank. These sturdy, reliable processing units are able to effectively handle most of the day-to-day operations of stations, starships, and stargates. "},
            //new Equipment { Title = "Nano-Factory",			Quantity = 200,		Description = "Only the highly advanced Ukomi superconductor can be rendered small enough for use in nano-factories, microscopic devices programmed to absorb and recycle ambient material into useful matter. Each factory is built from reactive metals, ensuring that they interact properly – or not at all – with their environment, while a mote of industrial explosive automatically destroys them when they have completed their task. "},
            //new Equipment { Title = "Integrity Response Drones", Quantity = 5000, Description = "Hull breaches are a constant, serious threat during space travel, as well as a dangerous reality to orbital stations, which are too massive to avoid incoming objects. Integrity response drones help mitigate that threat by providing the automated, immediate application of sealants to any detected impact or pressure fracture in the structure they patrol. "}                

            //List<Project> projects = new List<Project>
            //         {
            //             new Project { Name = "Organic Mortar Applicators", Term = 65, Location = "Alaska", DateOfBeginning = new DateTime(2017,1,21), Cost = 10000, CodeName = "OMA-17", Description = "While nanites are ideal for many forms of construction, sealing joints between large structural bulkheads is a job best left to organic mortar, a thick gel that actively permeates every microscopic gap between two parts. Due to the aggressive nature of the genetically engineered bacteria that intelligently guides into place the hardening condensate material, this paste is extremely hazardous to humans and must be applied by robots.",
            //                 Scientists = new List<Scientist> { scientists.Find(x => x.Name == "Agalle Vacoloure"), scientists.Find(x => x.Name == "Arcadia Mcguire"), scientists.Find(x => x.Name == "Vienna Jacobs"), scientists.Find(x => x.Name == "Gemma Ross"), scientists.Find(x => x.Name == "Summer Good") },
            //                 Technicians = new List<Technician> { technicians.Find(x => x.Name == "Coco Garza"), technicians.Find(x => x.Name == "Juniper Parks"), technicians.Find(x => x.Name == "Anique Tucker"), technicians.Find(x => x.Name == "Fern Macias"), technicians.Find(x => x.Name == "Summer Ramirez"), technicians.Find(x => x.Name == "Morena Malone") },
            //                 Samples = new List<Sample> { samples.Find(x => x.Title == "Bacteria"), samples.Find(x => x.Title == "Condensates") },
            //                 Equipments = new List<Equipment> { equipments.Find(x => x.Title == "Robotics") } },

            //             new Project { Name = "Integrity Response Drones", Term = 80, Location = "New Zeland", DateOfBeginning = new DateTime(2018,3,27), Cost = 23000, CodeName = "IRD-24", Description = "Hull breaches are a constant, serious threat during space travel, as well as a dangerous reality to orbital stations, which are too massive to avoid incoming objects. Integrity response drones help mitigate that threat by providing the automated, immediate application of sealants to any detected impact or pressure fracture in the structure they patrol.",
            //                 Scientists = new List<Scientist> { scientists.Find(x => x.Name == "Abenar Zindob"), scientists.Find(x => x.Name == "Sorrell Russell"), scientists.Find(x => x.Name == "Bela Doherty"), scientists.Find(x => x.Name == "Summer Good"), scientists.Find(x => x.Name == "Scout Vikander") },
            //                 Technicians = new List<Technician> { technicians.Find(x => x.Name == "Anique Tucker"), technicians.Find(x => x.Name == "Fern Macias"), technicians.Find(x => x.Name == "Kimberly Shepherd"), technicians.Find(x => x.Name == "Shannon Mccarthy"), technicians.Find(x => x.Name == "Terra Parkinson") },
            //        Samples = new List<Sample> { samples.Find(x => x.Title == "Gel-Matrix Biopaste") },
            //        Equipments = new List<Equipment> { equipments.Find(x => x.Title == "Planetary Vehicles"), equipments.Find(x => x.Title == "Hazmat Detection Systems") } },

            //             new Project { Name = "Wetware Mainframe", Term = 165, Location = "USA", DateOfBeginning = new DateTime(2012,8,13), Cost = 500000, CodeName = "WMF-00-19", Description = "So advanced and energy-demanding are wetware mainframes that they require vehicle-scale power cores and the constant attention of maintenance personnel. When operating at peak performance levels, nothing in New Eden can match the raw computing power of these machines, from calculating warp coordinates to administrating the core functions of an entire space station.",
            //                 Scientists = new List<Scientist> { scientists.Find(x => x.Name == "Delta Downs"), scientists.Find(x => x.Name == "Bela Dohert"), scientists.Find(x => x.Name == "Carson Kumar"), scientists.Find(x => x.Name == "Dale Tyler") },
            //                 Technicians = new List<Technician> { technicians.Find(x => x.Name == "Anique Tucker"), technicians.Find(x => x.Name == "Fern Macias"), technicians.Find(x => x.Name == "Olive Haworth"), technicians.Find(x => x.Name == "Shannon Mccarthy"), technicians.Find(x => x.Name == "Snow Prentice"), technicians.Find(x => x.Name == "Morena Malone"), technicians.Find(x => x.Name == "Sienna Frazier") },
            //                 Samples = new List<Sample> { samples.Find(x => x.Title == "Cryoprotectant Solution"), samples.Find(x => x.Title == "Biotech Research Reports")  },
            //                 Equipments = new List<Equipment> { equipments.Find(x => x.Title == "Supercomputers") } }
            //};
            //db.Projects.AddRange(projects);
            ////db.SaveChanges();          

            //scientists.Find(x => x.Name == "Agalle Vacoloure").Projects = scientists.Find(x => x.Name == "Arcadia Mcguire").Projects = scientists.Find(x => x.Name == "Vienna Jacobs").Projects = scientists.Find(x => x.Name == "Gemma Ross").Projects = scientists.Find(x => x.Name == "Summer Good").Projects =
            //    technicians.Find(x => x.Name == "Coco Garza").Projects = technicians.Find(x => x.Name == "Juniper Parks").Projects = technicians.Find(x => x.Name == "Anique Tucker").Projects = technicians.Find(x => x.Name == "Fern Macias").Projects = technicians.Find(x => x.Name == "Summer Ramirez").Projects = technicians.Find(x => x.Name == "Morena Malone").Projects =
            //        samples.Find(x => x.Title == "Bacteria").Projects = samples.Find(x => x.Title == "Condensates").Projects =
            //            equipments.Find(x => x.Title == "Robotics").Projects = new List<Project> { projects.Find(x => x.Name == "Organic Mortar Applicators") };

            //scientists.Find(x => x.Name == "Abenar Zindob").Projects = scientists.Find(x => x.Name == "Sorrell Russell").Projects = scientists.Find(x => x.Name == "Bela Doherty").Projects = scientists.Find(x => x.Name == "Summer Good").Projects = scientists.Find(x => x.Name == "Scout Vikander").Projects =
            //    technicians.Find(x => x.Name == "Anique Tucker").Projects = technicians.Find(x => x.Name == "Fern Macias").Projects = technicians.Find(x => x.Name == "Kimberly Shepherd").Projects = technicians.Find(x => x.Name == "Shannon Mccarthy").Projects = technicians.Find(x => x.Name == "Terra Parkinson").Projects =
            //        samples.Find(x => x.Title == "Gel-Matrix Biopaste").Projects =
            //            equipments.Find(x => x.Title == "Planetary Vehicles").Projects = equipments.Find(x => x.Title == "Hazmat Detection Systems").Projects = new List<Project> { projects.Find(x => x.Name == "Integrity Response Drones") };

            //scientists.Find(x => x.Name == "Delta Downs").Projects = scientists.Find(x => x.Name == "Bela Dohert").Projects = scientists.Find(x => x.Name == "Carson Kumar").Projects = scientists.Find(x => x.Name == "Dale Tyler").Projects =
            //    technicians.Find(x => x.Name == "Anique Tucker").Projects = technicians.Find(x => x.Name == "Fern Macias").Projects = technicians.Find(x => x.Name == "Olive Haworth").Projects = technicians.Find(x => x.Name == "Shannon Mccarthy").Projects = technicians.Find(x => x.Name == "Snow Prentice").Projects = technicians.Find(x => x.Name == "Morena Malone").Projects = technicians.Find(x => x.Name == "Sienna Frazier").Projects =
            //        samples.Find(x => x.Title == "Cryoprotectant Solution").Projects = samples.Find(x => x.Title == "Biotech Research Reports").Projects =
            //            equipments.Find(x => x.Title == "Supercomputers").Projects = new List<Project> { projects.Find(x => x.Name == "Wetware Mainframe") };


            //db.Entry(projects[0]).State = db.Entry(projects[1]).State = db.Entry(projects[2]).State = EntityState.Modified;

            //db.Entry(scientists[0]).State = db.Entry(scientists[5]).State = db.Entry(scientists[8]).State = db.Entry(scientists[15]).State = db.Entry(scientists[20]).State =
            //	db.Entry(technicians[0]).State = db.Entry(technicians[1]).State = db.Entry(technicians[2]).State = db.Entry(technicians[3]).State = db.Entry(technicians[15]).State = db.Entry(technicians[24]).State =
            //		db.Entry(samples[15]).State = db.Entry(samples[43]).State = 
            //			db.Entry(equipments[10]).State = EntityState.Modified;

            //scientists[0].Projects = scientists[5].Projects = scientists[8].Projects = scientists[15].Projects = scientists[20].Projects =
            //             technicians[0].Projects = technicians[1].Projects = technicians[2].Projects = technicians[3].Projects = technicians[15].Projects = technicians[24].Projects =
            //                 samples[15].Projects = samples[43].Projects =
            //                     equipments[10].Projects = new List<Project> { projects[0] };

            //db.SaveChanges(); // here project 2: 5 scientist -> 4, 5 technicians -> 3

            //db.Entry(scientists[2]).State = db.Entry(scientists[14]).State = db.Entry(scientists[19]).State = db.Entry(scientists[20]).State = db.Entry(scientists[29]).State =
            //	db.Entry(technicians[2]).State = db.Entry(technicians[3]).State = db.Entry(technicians[12]).State = db.Entry(technicians[14]).State = db.Entry(technicians[21]).State =
            //		db.Entry(samples[44]).State = 
            //			db.Entry(equipments[11]).State = db.Entry(equipments[13]).State = EntityState.Modified;

            //scientists[2].Projects = scientists[14].Projects = scientists[19].Projects = scientists[20].Projects = scientists[29].Projects =
            //             technicians[2].Projects = technicians[3].Projects = technicians[12].Projects = technicians[14].Projects = technicians[21].Projects =
            //                 samples[44].Projects =
            //                     equipments[11].Projects = equipments[13].Projects = new List<Project> { projects[1] };

            //db.SaveChanges(); // here: 6 scientist -> 4, 5 technician -> 4

            //db.Entry(scientists[17]).State = db.Entry(scientists[19]).State = db.Entry(scientists[21]).State = db.Entry(scientists[28]).State =
            //	db.Entry(technicians[2]).State = db.Entry(technicians[3]).State = db.Entry(technicians[6]).State = db.Entry(technicians[14]).State = db.Entry(technicians[22]).State = db.Entry(technicians[24]).State = db.Entry(technicians[26]).State =
            //		db.Entry(samples[45]).State = db.Entry(samples[46]).State =
            //			db.Entry(equipments[8]).State = EntityState.Modified;

            //scientists[17].Projects = scientists[19].Projects = scientists[21].Projects = scientists[28].Projects =
            //             technicians[2].Projects = technicians[3].Projects = technicians[6].Projects = technicians[14].Projects = technicians[22].Projects = technicians[24].Projects = technicians[26].Projects =
            //                 samples[45].Projects = samples[46].Projects =
            //                     equipments[8].Projects = new List<Project> { projects[2] };

            //db.SaveChanges(); 			
            //base.Seed(db);			
        }
	}
}
