// <auto-generated />
namespace NII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddnullchecktoProjectclassZpropertiesAddZPropertytoSampleClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddnullchecktoProjectclassZpropertiesAddZPropertytoSampleClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201806141657371_Add null check to Project-class Z-properties. Add Z-Property to Sample-Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
