// <auto-generated />
namespace NII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EquipmentstoEquipmentSampleQuantitytypeVARCHARtotypeINT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EquipmentstoEquipmentSampleQuantitytypeVARCHARtotypeINT));
        
        string IMigrationMetadata.Id
        {
            get { return "201806171640089_Equipments to Equipment; Sample.Quantity type VARCHAR to type INT."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
